meta:
  schema: v0.0.1
name: todolist
default_access: deny
models:
  - name: TodoItem
    description: Record of an item on the todo list
    fields:
      - name: subject
        type: string
        description: Todo item subject
      - name: description
        type: string
        description: Todo item description
    visibility_scope: owner
api:
  endpoints:
    - name: todo
      path: /todo
      type: model
      model: TodoItem
      access:
        - role: user
          action: allow
