#!/usr/bin/env python3

import sys
import requests

if len(sys.argv) == 1:
    r = requests.get("http://localhost:8888/api/github.famz/todolist/todo")
    print("\n".join(["- %s" % x['subject'] for x in r.json()]))
elif sys.argv[1] == '-c':
    completing = set(sys.argv[2:])
    r = requests.get("http://localhost:8888/api/github.famz/todolist/todo")
    for x in r.json():
        pk = x['pk']
        if x['subject'] in completing:
            data = {
                "pk": x['pk'],
            }
            r = requests.delete("http://localhost:8888/api/github.famz/todolist/todo",
                                json=data)
else:
    for item in sys.argv[1:]:
        data = {
            "subject": item,
        }
        r = requests.post("http://localhost:8888/api/github.famz/todolist/todo",
                          json=data)
        print(r)
